### ISSUE TITLE
Docs CSS Issues

### ISSUE THREAD

**Issue by deniseschannon** [rancherlabs/website-theme#2]
[x] Fix Headings Sizing

H2 - Looks Too Big
<img width="532" alt="screen shot 2018-04-18 at 11 36 38 am" src="https://user-images.githubusercontent.com/11410997/38951215-c55f1fba-42fc-11e8-9b96-3b5b40da7b40.png">

H3
<img width="520" alt="screen shot 2018-04-18 at 11 36 49 am" src="https://user-images.githubusercontent.com/11410997/38951223-cccd1e32-42fc-11e8-8775-d17010c506e1.png">

H4 - Too Small
<img width="196" alt="screen shot 2018-04-18 at 11 37 24 am" src="https://user-images.githubusercontent.com/11410997/38951245-e06f6710-42fc-11e8-94ba-8dfdfc09fcf1.png">

[ ] Numbered Lists are putting numbers in weird place - Example: http://localhost:9001/rancher/quick-start-guide/

<img width="647" alt="screen shot 2018-04-19 at 8 38 09 pm" src="https://user-images.githubusercontent.com/11410997/39029637-a4e24ce2-4411-11e8-9917-c8af5ef3842d.png">

[x] Bold isn't working `In markdown **test**, CSS - <strong></strong>`

<img width="295" alt="screen shot 2018-04-18 at 11 39 12 am" src="https://user-images.githubusercontent.com/11410997/38951327-24e012d2-42fd-11e8-804e-662655917825.png">

[ ] Padding around code blocks looks too big and do we really want light grey with green text as our code blocks? 

<img width="694" alt="screen shot 2018-04-18 at 11 40 06 am" src="https://user-images.githubusercontent.com/11410997/38951368-4858b25a-42fd-11e8-9b40-14125ed996bb.png">

[x] Line underneath Hyperlinks are too big!

<img width="133" alt="screen shot 2018-04-18 at 11 40 44 am" src="https://user-images.githubusercontent.com/11410997/38951392-56fd0ea0-42fd-11e8-9502-28cbb600e3c7.png">

**Comment by lvuch** [comment]
The numbered list issue is caused from line breaks in the markdown. Basically there doesn't need to be a space between each item otherwise it wraps them in p tag.

**Comment by deniseschannon** [comment]
Even when I remove the line breaks, it still gets wrapped in a p tag.

**Comment by deniseschannon** [comment]
the line breaks aren't enough:

check out this file. trying to delete them makes it look all crazy:

 os/installation/custom-builds/custom-kernels/

**Comment by deniseschannon** [comment]
list of files that have numbered lists in OS: 

https://github.com/rancher/docs/pull/26/files
